### ISSUE TITLE
[TB] Inverse Bevel not being applied to the slrdier rail and track

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#267] opened 2023-04-19 18:54 UTC
## Problem/Concern

* [link to problem content]()

**Comment by brycecurtis** [comment] 2023-04-24 17:24
Is this a dup of #243?

**Comment by evangk6** [comment] 2023-05-03 16:38
Indeed is a duplicate of https://github.com/discoverfinancial/a11y-theme-builder/issues/243 - cloising this one

**Closed as completed by evangk6** 2023-05-03 16:38 UTC
Labels: theme builder app
