### ISSUE TITLE
[SDK] Shadow variable names

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#562] opened 2023-09-18 16:19 UTC
## Problem/Concern

1.) The button-shadow variable is missing

2.) The following names need to be updated:
--popoverShadow > --popover-shadow
--sliderhandleShadow >. --sliderhandle-shadow
--barShadow > --sliderbar-shadow

3.) Remove these variables from Toast
--toast-bevel | var(--bevel-0) | Bevel for toast
--toast-boxshadow

4.) Remove these variables from Chips
--switch-height | var(--spacing-3) | Currently unused
--switch-radius | 3 | Currently unused
--switch-bar-height | 0.5 | Currently unused
--switch-bar-radius | 0.5

* [link to problem content]()

**Comment by smithbk** [comment] 2023-09-18 17:50
I checked in fixes for 2, 3, and 4.  For 1, I didn't see any issues so I added a specific test case to confirm that button-shadow was being emitted when the button shadow property was being set to something other than it's default value of "None" and it was.  So please retry that.  If it is still not being set, then I will need the debug logs to try to figure out what is happening.

**Comment by smithbk** [comment] 2023-09-18 18:12
Also, not mentioned in this issue but you had said that the "--background" CSS variable's value had an opacity of 0.6 but it should be 1.0.  I am not able to reproduce that in my test code.  The value of "--background" is the color's hex value which is an implict opacity of 1.0.  So please make sure that the opacity of 0.6 isn't coming from some place else and then if you are still seeing it, provide the logs for me to analyze.

**Comment by aaronreed708** [comment] 2023-09-19 21:58
It looks like all of the css variables mentioned at the opening of the issue are now present.  So that is fixed.

I see var(--background) has opacity 0.6 in the Sample design system but not if I create a new design system.  It also had that value prior to Lise's changes (looking at an older docker image that I have), so that is not new.  Not sure why.  I see where in [data-background="primary"] it sets --backgound to var(--primary-background) which has the (255, 255, 255, 0.6) value.  But I'm not sure where that is coming from.  In :root --primary-background is set to var(--background).

**Comment by aaronreed708** [comment] 2023-09-19 22:31
I tracked it down.  The lightModeBackground for the design system "Sample" was committed with an opacity 0.6 with the commit https://github.com/discoverfinancial/a11y-theme-builder/commit/4df1791902d65d48710f1e36265a272400e3abff.

So the question is now, what do we do?  If this is definitely something that we don't want, I can go in and hand tweak that one variable.

**Comment by aaronreed708** [comment] 2023-09-20 05:46
Hand tweaking didn't work.  Will ask Bryce if he has experience updating that DB.

**Comment by aaronreed708** [comment] 2023-09-20 16:17
Background opacity issue in Sample design system fixed in https://github.com/discoverfinancial/a11y-theme-builder/commit/03174b64ea1a8cd269c16fbcbd65e7a15f32c073.  Closing this issue.

**Closed as completed by aaronreed708** 2023-09-20 16:17 UTC
Labels: bug
