### ISSUE TITLE
[REQUEST] Integrate Prettier for Consistent Code Formatting

### ISSUE THREAD

**Issue by ravjot07** [finos/a11y-theme-builder#876] opened 2024-05-09 20:41 UTC
## Suggestion/Concern
Proposing the integration of Prettier into the a11y-theme-builder project to ensure consistent code styling, reduce formatting inconsistencies, and improve the overall quality of the codebase.

## Proposed Solution
 **Install Prettier**: Add Prettier as a dev dependency.
   ```bash
   npm install --save-dev prettier
```

And then formatting the codebase

**Comment by Sweetdevil144** [comment] 2024-05-12 08:29
Duplicate of #856

**Comment by aaronreed708** [comment] 2024-05-14 17:55
> Duplicate of #856

@Sweetdevil144  Why do you think this is a duplicate of #856?  They seem to be complimentary efforts.

**Comment by PaulaPaul** [comment] 2024-05-23 13:58
Has there been consideration for other linting/formatting solutions, or were we just defaulting to prettier? If we can take some time and solve this holistically we might still wind up with prettier and eslint but it may be worth outlining what alternatives were considered?
[Biome?](https://biomejs.dev/)

Also related to #897

**Comment by ravjot07** [comment] 2024-05-23 16:38
should i work on adding boime ??

**Comment by aaronreed708** [comment] 2024-05-23 23:17
> should i work on adding boime ??

I believe that @PaulaPaul just wants to make sure that you considered alternatives.  Especially given that we are also doing Linter work.

**Comment by aaronreed708** [comment] 2024-06-29 18:17
Read up a little on Biome: https://medium.com/navara/biome-the-faster-lint-and-formatting-alternative-to-prettier-12fcf8b122b9.  Specifically it mentions that:
> Rust-based linters currently lack the comprehensiveness of type-checked lint rules provided by ESLint. This means that while they can identify syntax errors and common style issues, they may miss problems that rely on type information.

Our project is written in typescript to realize the benefits of typing our javascript.  The main gain using Biome seems to be performance which, I don't believe, impacts us much with our smallish code base.  Prettier is well adopted and already lives in the experience of most developers that we are going to attract as contributors.  So I'm thinking that we stick with Prettier for now.  We can always switch as Biome (or any other alternative) gains traction.

**Comment by aaronreed708** [comment] 2024-07-26 05:28
@ravjot07 could you verify that we can close this issue that you opened?

**Closed as completed** 2024-08-21 02:25 UTC
Labels: theme builder app
