### ISSUE TITLE
The --primaryDarkBG and --secondaryDarkBG are not rendering as the correct colors

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#100] opened 2023-04-11 17:43 UTC
## Problem/Concern
The colors for the --primaryDarkBG and --secondaryDarkBGshould be darker versions of the primary-900 color and they just look grey

* [link to problem content]()

**Comment by aaronreed708** [comment] 2024-01-04 16:15
This is a very old issue.  @lwnoble can you verify that this is still a problem?

**Comment by evangk6** [comment] 2024-01-19 00:33
Duplicate of #656

**Closed as completed by evangk6** 2024-01-19 00:33 UTC
Labels: bug, theme builder app, awaiting feedback
